services:
  - type: web
    name: finreg-rag-api
    runtime: python
    buildCommand: pip install torch==2.2.2+cpu --index-url https://download.pytorch.org/whl/cpu && pip install -r requirements-render.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GROQ_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false